mvc/urls.py
from django.conf.urls import url,re_path
from django.urls import path
from . import views


urlpatterns = [
    url(r'addSite/', views.addSite),
    url(r'addExam/', views.addExam),
    re_path(r'upload/(?P<examId>[0-9]+)$', views.upload, name = 'upload'),
    re_path(r'^download/(?P<fileId>[0-9]+)/$', views.download, name = 'download'),
    #url(r'^getExamList/?P<pageIndex>(\d+)/$', views.getExamList),
    re_path(r'^getExamList/(?P<pageIndex>[0-9]*)/$', views.getExamList),
    #path('setPrintService/<examId>', views.setPrintService),
    re_path(r'^setPrintService/(?P<examId>[0-9]+)/$', views.setPrintService, name = 'setPrintService'), 
    re_path(r'^savePrintTemplate/(?P<examId>[0-9]+)/$', views.savePrintTemplate, name = 'savePrintTemplate'), 
    re_path(r'^printMain/(?P<examId>[0-9]+)/$', views.printMain, name = 'views.printMain'), 
    url(r'4', views.addExamResult, name = 'add-exam-result'),
    url(r'5', views.addSiteResult, name = 'add-site-result'),
]

pems/urls.py
from django.contrib import admin
from django.urls import path,re_path
from django.conf.urls import url
from django.conf.urls import include
from mvc import views


urlpatterns = [
    url(r'mvc/', include('mvc.urls')),
    path('admin/', admin.site.urls),
    url(r'^tinymce/', include('tinymce.urls')),
    path('ckeditor/',include('ckeditor_uploader.urls')),
    url(r'', views.index),
    
]

mvc/models.py
from django.db import models
from django.utils import timezone
from tinymce.models import HTMLField
#from ckeditor_uploader.fields import RichTextUploadingField

# Create your models here.
#考试类别
TYPE_CHOICES = (
    ("公务员考录" , "公务员考录"),
    ("事业招聘" , "事业招聘"), 
    ("专业技术资格" , "专业技术资格"),
    ("社会化考试" , "社会化考试"),
)
#考试形式
METHOD_CHOICES = (
    ("面试" , "面试"),
    ("笔试" , "笔试"), 
    ("机考" , "机考"),
    ("其他" , "其他"),
)

class User(models.Model):#用户模型类
    id = models.AutoField(primary_key = True)
    name = models.CharField('用户名', max_length = 50)
    realName = models.CharField('真实姓名', max_length = 50)
    phone = models.CharField('手机号码', max_length = 11)

class Exam(models.Model):  #考试模型类
    id = models.AutoField(primary_key = True)
    name = models.CharField('考试名称', max_length = 100)
    date = models.DateField('考试日期')
    subject_1_Name = models.CharField('考试科目', max_length = 100, blank = True, null = True)
    subject_1_Time = models.CharField('科目时间', max_length = 100, blank = True, null = True)
    subject_2_Name = models.CharField('考试科目', max_length = 100, blank = True, null = True)
    subject_2_Time = models.CharField('科目时间', max_length = 100, blank = True, null = True)
    subject_3_Name = models.CharField('考试科目', max_length = 100, blank = True, null = True)
    subject_3_Time = models.CharField('科目时间', max_length = 100, blank = True, null = True)
    siteName = models.CharField('考点名称', max_length = 100, blank = True, null = True)
    siteAddress = models.CharField('考点地址', max_length = 100, blank = True, null = True)
    examineeNum = models.IntegerField('考生人数', blank = True, null = True)
    examType = models.CharField('考试类别', max_length = 20, choices = TYPE_CHOICES, default = TYPE_CHOICES[3])
    examMethod = models.CharField('考试形式', max_length = 20, choices = METHOD_CHOICES, default = METHOD_CHOICES[1])
    remarks = models.TextField('备注', max_length = 500, blank = True, null = True)

class printTemplate(models.Model): #笔试准考证设置信息
    id = models.AutoField(primary_key = True)
    exam = models.OneToOneField(Exam, on_delete = models.CASCADE, verbose_name = '关联考试', blank = True, null = True)  
    beginTime = models.DateTimeField("开始打印时间", auto_now = False, auto_now_add = False, null = True, blank = True)
    endTime = models.DateTimeField("结束打印时间", auto_now = False, auto_now_add = False, null = True, blank = True)
    printType = models.CharField('模板类别', max_length = 20, choices = TYPE_CHOICES, default = TYPE_CHOICES[3])
    content = HTMLField('模板内容')
    ifBase = models.BooleanField("是否基础模板", default = '0') #0是非基础模板,1是基础模板
    state = models.BooleanField("是否启动", default = '0') #0未启动，1启动中
    loginURL = models.CharField('登录网址', max_length = 200, blank = True, null = True)
    

class Examinee(models.Model): #考生模型类
    id = models.AutoField(primary_key = True)
    theExam = models.ForeignKey(Exam, on_delete = models.CASCADE, verbose_name = '关联考试')
    name = models.CharField('考生姓名', max_length = 20)
    IDNO = models.CharField('身份证号', max_length = 18)
    ATID = models.CharField('准考证号', max_length = 11)
    applyUnit = models.CharField("报考单位", max_length = 100, blank = True, null = True)
    applyPosition = models.CharField("报考职位", max_length = 100, blank = True, null = True)
    phone = models.CharField("手机号码", max_length = 11, blank = True, null = True)
    ifQuery = models.BooleanField("是否已查询", default = '0') #0未查询，1已查询
    ifPrint = models.BooleanField("是否已打印", default = '0') #0未打印，1已打印

class ExamSite(models.Model):  #考点模型类
    name = models.CharField('考点名称', max_length = 100)
    address = models.CharField('考点地址', max_length = 100)
    roomNum = models.IntegerField('考场数')
    roomMaxNum = models.IntegerField('最大考场数')
    chiefName = models.CharField('主考', max_length = 20)
    chiefPhone = models.CharField('主考联系方式', max_length = 11)
    directorName = models.CharField('考务负责人', max_length = 20)
    directorPhone = models.CharField('考务联系方式', max_length = 11)
    ifStandardized = models.BooleanField('是否标准化考场')
    remarks = models.TextField('备注', max_length = 500)

class ExamPerson(models.Model): #考务人员模型类
    name = models.CharField('姓名', max_length = 20)
    workUnit = models.CharField('工作单位', max_length = 100)
    post = models.CharField('工作职务', max_length = 30) 
    phone = models.CharField('联系方式', max_length = 11)
    role = models.CharField('考务岗位', max_length = 20)
    ifTemporary = models.BooleanField('是否临聘人员') 
    grade = models.IntegerField('评分')
    remarks = models.TextField('备注', max_length = 500)
    
class ExamStuff(models.Model): #考务材料模型类
    name = models.CharField('材料名称', max_length = 20)
    amount = models.IntegerField('数量')
    stuffType = models.CharField('类别', max_length = 20) #消耗品|非消耗品
    remarks = models.TextField('备注', max_length = 500)

class FileInfo(models.Model):
    examId = models.CharField('关联考试ID', max_length = 20, blank=True)
    name = models.CharField('文件名', max_length = 50)
    size = models.DecimalField("文件大小", max_digits = 10, decimal_places = 0)
    path = models.CharField("文件路径", max_length = 200)
    time = models.DateTimeField("上传时间", default = timezone.now())

class testModel(models.Model):
    content = HTMLField('内容')

mvc/forms.py
from django.forms import ModelForm
from django import forms
from mvc.models import *
from tinymce.widgets import TinyMCE
from django.contrib.admin import widgets

class SiteForm(ModelForm):
    class Meta:
        model = ExamSite
        fields = '__all__'

class ExamForm(ModelForm):
    class Meta:
        model = Exam
        fields = '__all__'

class UploadForm(forms.Form):
    file = forms.FileField(widget = forms.ClearableFileInput(attrs = {'multiple': True}), label = '选择文件...', help_text = '最大100M')

class PTForm(ModelForm):
    #content = forms.CharField(widget=TinyMCE(attrs={'cols': 50, 'rows': 10}))
    #beginTime = forms.DateTimeField(required = True, label = '开始打印时间', widget = widgets.AdminSplitDateTime)
    #endTime = forms.DateTimeField(required = True, label = '结束打印时间', widget = widgets.AdminSplitDateTime)
    class Meta:
        model = printTemplate
        fields = ('beginTime','endTime','content','state','loginURL')

mvc/views.py
import os
from django.shortcuts import render,redirect
from django.http import HttpResponse,FileResponse
from django.http import HttpResponseRedirect
from django.utils.http import urlquote
from django.urls import reverse
from django.views.decorators.csrf import csrf_exempt
from django.template import loader
from django.core.paginator import Paginator
from mvc.forms import *
from utils.dataUtil import excelImport2Db
from django.utils import timezone

# Create your views here.
PAGE_SIZE = 3

def index(request):
    return HttpResponse("<h1>欢迎来到人事考试管理系统！</h1>")

def addExamResult(request):
    return HttpResponse("<h1>考试项目已成功保存！</h1>")

def addSiteResult(request):
    return HttpResponse("<h1>考点资源已成功保存！</h1>")

# Create your views here.
@csrf_exempt
def addExam(request):
    if request.method == 'POST':
        form = ExamForm(request.POST)
        if form.is_valid():
            exam = form.save()
            exam.save()
            return HttpResponseRedirect(reverse('add-exam-result'))
    else:
        form = ExamForm()
    PROJECT_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__))) #项目根路径
    return render(request, os.path.join(PROJECT_ROOT, 'mvc/templates', 'addExam.html'), {'form':form})  

@csrf_exempt
def addSite(request):
    if request.method == 'POST':
        form = SiteForm(request.POST)
        if form.is_valid():
            site = form.save()
            site.save()
            return HttpResponseRedirect(reverse('add-site-result'))
    else:
        form = SiteForm()
    PROJECT_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__))) #项目根路径
    return render(request, os.path.join(PROJECT_ROOT, 'mvc/templates', 'addSite.html'), {'form':form})  

@csrf_exempt
def getExamList(request, pageIndex):
    #print("the pageIndex is {}".format(pageIndex))
    if(pageIndex == ''):
        pageIndex = 1
    else:
        pageIndex = int(pageIndex)
    #_template = loader.get_template('examList.html')
    examList = Exam.objects.all().order_by('id')  #'-id'倒序
    _paginator = Paginator(examList, PAGE_SIZE)
    currentPage = _paginator.get_page(pageIndex)
    context = {
        'examList' :  currentPage,
        'request' :  request,
        'pagiator' :  _paginator,
        'has_pages' :  _paginator.num_pages > 1,
        'has_next' :  _paginator.page(pageIndex).has_next(),
        'has_prev' : _paginator.page(pageIndex).has_previous(),
        'page_index' : pageIndex,
        'page_next' : pageIndex + 1,
        'page_prev' : pageIndex - 1,
        'page_count' : _paginator.num_pages,
        'row_count' : _paginator.count,
        'page_nums' : range(_paginator.num_pages + 1)[1:],
    }
    #_output = _template.render(_context)
    #return HttpResponse(_output)
    #index_page(request, pageIndex)
    return render(request, "examList.html", context)


@csrf_exempt
def setPrintService(request, examId):
    currentExam = Exam.objects.get(id = examId)
    relatePT = printTemplate.objects.filter(exam_id = examId) #查询当前考试对应的打印模板
    if(relatePT.exists()):
        dic = {'beginTime' : relatePT[0].beginTime,'endTime' : relatePT[0].endTime, 'content': relatePT[0].content, 'state':relatePT[0].state, 'loginURL':relatePT[0].loginURL }
        ptForm = PTForm(dic) 
    else:  #相对应的打印模板还未保存
        basePT = printTemplate.objects.filter(printType = currentExam.examType, ifBase = '1')
        dic = {'beginTime' : basePT[0].beginTime,'endTime' : basePT[0].endTime, 'content': basePT[0].content }
        ptForm = PTForm(dic)   
    #print("The currentExam name is {}".format(currentExam.name))
    #最近上传的导入数据文件
    fileInfoList = FileInfo.objects.filter(examId = examId).order_by('-time')
    #print("The last upload file name is {}".format(lastFileInfo[0].name))
    if(len(fileInfoList) > 0):
        lastFile = fileInfoList[0]
    else:
        lastFile = 'none'
    context = {
        'currentExam' :  currentExam,
        'lastFile' : lastFile,
        'ptForm' : ptForm,
    }
    return render(request, "printService.html", context)

@csrf_exempt
def upload(request, examId):
    PROJECT_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__))) #项目根路径
    currentExam = Exam.objects.get(id = examId)
    if request.method == 'POST':
        form = UploadForm(request.POST, request.FILES)
        if form.is_valid():
            files = request.FILES.getlist('file')
            for eachFile in files:
                fileInfo = FileInfo(examId = examId, name = eachFile.name, size = 1 if 0 < eachFile.size < 1024 else eachFile.size / 1024, path = os.path.join(PROJECT_ROOT, 'upload'))
                fileInfo.save()
                destination = open(os.path.join(os.path.join(PROJECT_ROOT, 'upload/'), eachFile.name), 'wb+')
                for chunk in eachFile.chunks():
                    destination.write(chunk)
                    destination.close()
                excelImport2Db(os.path.join(os.path.join(PROJECT_ROOT, 'upload/'), eachFile.name), examId)#excel文件数据导入pems-db
    #return HttpResponse("<h1>文件导入成功</h1>") #应返回打印设置页面
    #return redirect('http://127.0.0.1:8000/mvc/setPrintService/1/') 
    currentExam = Exam.objects.get(id = examId) 
    fileInfoList = FileInfo.objects.filter(examId = examId).order_by('-time')
    if(len(fileInfoList) > 0):
        lastFile = fileInfoList[0]
    else:
        lastFile = 'none'
    context = {
        'currentExam' :  currentExam,
        'lastFile' : lastFile,
    }
    return render(request, "printService.html", context)

@csrf_exempt
def download(request, fileId):
    fileInfo = FileInfo.objects.get(id = fileId)    
    filePath = os.path.join(fileInfo.path, fileInfo.name)   
    file = open(filePath, 'rb')
    response = FileResponse(file)
    response['Content-Disposition'] = 'attachment;filename="%s"' % urlquote(fileInfo.name)
    return response  

@csrf_exempt
def savePrintTemplate(request, examId):
    currentExam = Exam.objects.get(id = examId)
    if request.method == 'POST':
        #ptForm = PTForm(request.POST)
        #print("the endTime is {}".format(request.POST))
        #print("the endTime is {}".format(request.POST['endTime']))
        #if ptForm.is_valid():
        if(request.POST['state'] == 'on'):
            currentState = 1
        else:
            currentState = 0
        relatePT = printTemplate.objects.filter(exam_id = examId) #查询当前考试对应的打印模板
        if(relatePT.exists()): 
            relatePT[0].beginTime = request.POST['beginTime']
            relatePT[0].endime = request.POST['endTime']
            relatePT[0].content = request.POST['content'] 
            relatePT[0].state = request.POST['state']
            relatePT[0].loginURL = request.POST['loginURL']
            relatePT[0].save()
        else:
            PT = printTemplate(exam_id = examId,
                           printType = currentExam.examType,
                           beginTime = request.POST['beginTime'], 
                           endTime = request.POST['endTime'], 
                           content = request.POST['content'], 
                           state = currentState,
                           loginURL = "http://127.0.0.1/printLogin/" + examId + "/"
                           )                  
            PT.save()
        return HttpResponseRedirect(reverse('add-site-result'))

@csrf_exempt
def printMain(request, examId):
    currentExam = Exam.objects.get(id = examId)
    context = {
        'currentExam' :  currentExam,
    }
    return render(request, "printMain.html", context)

mvc/templates/addExam.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>新增考试项目</title>
</head>

<body>
    <form action = "?" method = "post">
        {% csrf_token %}
        <fieldset>
            <legend>请输入并提交</legend>
                {{ form.as_p }}
                <input type = "submit", value = "submit" />
        </fieldset>
    </form>
</body>

</html>

mvc/templates/addSite.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>新增考点资源</title>
</head>

<body>
    <form action = "?" method = "post">
        {% csrf_token %}
        <fieldset>
            <legend>请输入并提交</legend>
                {{ form.as_p }}
                <input type = "submit", value = "submit" />
        </fieldset>
    </form>
</body>

</html>

mvc/templates/examList.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>考试项目列表</title>
</head>

<body>
    <div>
        <h1>这是考试项目列表页面</h1>
        <ol style = "list-style:none">
            {% for eachExam in examList %}
            <li>
                {{ eachExam.id }}  {{ eachExam.name }} {{ eachExam.examMethod }}  {{ eachExam.date }} 
                {% ifequal eachExam.examMethod '笔试' %}
                    <a href="/mvc/setPrintService/{{ eachExam.id }}/"><input type="button" value='准考证打印设置'></a>
                {% else %}
                    <a href="/mvc/setPrintService/{{ eachExam.id }}/"><input type="button" value='通知书打印设置'></a>
                {% endifequal%}
            </li>
            {% endfor %}
        </ol>
    </div>
    <div>
        {% include 'control/pagebar.html' %}
    </div>
</body>

</html>

mvc/templates/printMain.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <div>
        { ptForm.content }
    </div>
</body>
</html>

mvc/templates/printService.html
<!DOCTYPE html>
<html lang='en'>

<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!--<script type="text/javascript" src="/static/ckeditor/ckeditor-init.js" data-ckeditor-basepath="/static/ckeditor/ckeditor/" id="ckeditor-init-script"></script>
    <script type="text/javascript" src="/static/ckeditor/ckeditor/ckeditor.js"></script> -->
    <script type="text/javascript" src="/static/tiny_mce/tiny_mce.js"></script>
    <script type="text/javascript" src="/static/django_tinymce/jquery-1.9.1.min.js"></script>
    <script type="text/javascript" src="/static/django_tinymce/init_tinymce.js"></script>
    <script type="text/javascript" src="{% static '/jquery/jquery-3.0.0.min.js' %}"></script>
    <!-- jquery
    <link href="{% static '/jquery/jquery-ui.min.css' %}" rel="stylesheet" />
    <link href="{% static '/jquery/jquery-ui-timepicker-addon.min.css' %}" rel="stylesheet"/>
    <script type="text/javascript" src="{% static '/jquery/jquery-ui.min.js' %}"></script>
    <script type="text/javascript" src="{% static '/jquery/jquery-ui-timepicker-addon.min.js' %}"></script>
    <script type="text/javascript" src="{% static '/jquery/jquery-ui-timepicker-zh-CN.js' %}"></script>
    -->
    <link  href="{% static '/bootstrap/bootstrap.min.css' %}" rel="stylesheet">
    <link  href="{% static '/bootstrap/bootstrap-datetimepicker.min.css' %}" rel="stylesheet">
    <script src="{% static '/bootstrap/bootstrap.min.js' %}"></script>
    <script src="{% static '/bootstrap/bootstrap-datetimepicker.min.js' %}"></script>
    <script src="{% static '/bootstrap/bootstrap-datetimepicker.zh-CN.js' %}"></script>
    
    <title>打印设置页面</title>
    <script type="text/javascript">
        $(document).ready(function(){
           $('#id_beginTime').datetimepicker({
                format: 'yyyy-mm-dd hh:ii',
                language:'zh-CN'
           });
           $('#id_endTime').datetimepicker({
                format: 'yyyy-mm-dd hh:ii',
                language:'zh-CN'
           });
        });

    </script>
    
</head>

<body>
    <div>当前考试名称: {{currentExam.name}} &nbsp;&nbsp;考试形式:{{currentExam.examMethod}}
        <a href="/mvc/download/1/"><input type="button" value='数据模板下载'></a></div>
    <div>
        最新导入的数据文件: 
        {% ifequal lastFile 'none' %}
            未导入数据文件！
        {% else %}
            {{ lastFile.name }} 导入时间: {{ lastFile.time }} 
        {% endifequal %}
    </div>
    
    <form enctype="multipart/form-data" action="upload/{{currentExam.id}}" method="post">
        {% csrf_token %}
        <p><input type="file" name="file"><input type="submit" name="上传文件"></p>
        
    </form>
    
    <div>
       
        <form action = "../../savePrintTemplate/{{currentExam.id}}/" method = "post">
            {% csrf_token %}
            <!--<fieldset>
                <legend>打印设置: </legend> -->
                {{ ptForm.as_p }}
                <input type = "submit", value = "submit" />
          <!-- </fieldset >-->  
        </form>
    </div>
</body>

</html>